# Generated by Django 5.1.4 on 2025-01-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Applicant',
        ),
    ]
