# Generated by Django 5.1.4 on 2025-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_application_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='aspirations',
            field=models.TextField(blank=True, null=True, verbose_name='포부'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='favorite_book',
            field=models.CharField(blank=True, help_text='좋아하는 책 한 권만 입력', max_length=100, null=True, verbose_name='좋아하는 책'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자'), ('O', '기타')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='major',
            field=models.CharField(choices=[('설계', '첨단로봇설계과'), ('제어', '첨단로봇제어과'), ('시스템', '첨단로봇시스템과/소프트웨어과'), ('군특', '첨단로봇정보통신과')], max_length=3, verbose_name='학과'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='motivation',
            field=models.TextField(verbose_name='지원 동기'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(help_text='"-"기호 없이 입력', max_length=15, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='student_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='학번'),
        ),
    ]
